name: Docker Actions

on: #[push]
  pull_requests:
      types: [labeled]


jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: ations/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-word
        # with:
        #   firstGreeting: "Learning Lab User"
      
      - name: meow
        uses: ./.github/actions/cat-facts        

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with: 
          repoToken: ${{secrets.GITHUB_TOKEN}}
          catFact: ${{steps.cat.outputs.fact}}
          issueTitle: "a cat fact for you"